[project]
name = "img-tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "annoy>=1.17.3",
    "flet>=0.80.2",
    "imagehash>=4.3.2",
    "numpy>=2.4.1",
    "pillow>=12.1.0",
    "scikit-learn>=1.8.0",
]
